server.port=8081
server.servlet.context-path=/api/v1

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=restaurante1_db;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=YourStrong!Passw0rd
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Ejecutar schema.sql al iniciar
spring.sql.init.mode=always

# Logging
logging.level.com.restaurante1.api=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG
