spring.application.name=ristorino-backend
server.port=8080

# --- Conexión JDBC (SQL Server) ---
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ristorino_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# --- Logging para ver las consultas SQL en consola (Útil para debug) ---
logging.level.org.springframework.jdbc=DEBUG