# =========================================================
# CONFIGURACION DEL SERVIDOR
# =========================================================
# Puerto donde correra la API (puedes usar 8080 o el que prefieras)
server.port=8080
# Prefijo de la URL para todos los endpoints (Buena practica)
server.servlet.context-path=/api/v1


# =========================================================
# CONFIGURACION DE LA BASE DE DATOS (DATASOURCE)
# =========================================================
# Indica a Spring la URL de tu base de datos SQL Server.
# Reemplaza 'localhost' si tu DB esta en otro servidor.
# Reemplaza 'ristorinoDB' si usaste un nombre diferente.
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ristorinoDB;trustServerCertificate=true

# REEMPLAZA ESTO con tu usuario y contrasena de SQL Server
spring.datasource.username=sa
spring.datasource.password=123456

# Indica que driver especifico debe usar (el que agregamos como dependencia)
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


# =========================================================
# CONFIGURACION DE JPA (El "Bibliotecario")
# =========================================================
# Le dice a JPA que "dialecto" de SQL debe hablar (en este caso, SQL Server)
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect

# (Opcional, pero MUY recomendado para desarrollo)
# Muestra en la consola el SQL exacto que JPA esta generando.
spring.jpa.show-sql=true

# (Opcional) Permite a Hibernate (la implementacion de JPA) actualizar
# el esquema si cambias las entidades. 'update' es seguro para desarrollo.
spring.jpa.hibernate.ddl-auto=update
