# =========================================================
# CONFIGURACION DEL SERVIDOR
# =========================================================
# Puerto donde correra la API (puedes usar 8080 o el que prefieras)
server.port=8080
# Prefijo de la URL para todos los endpoints (Buena practica)
server.servlet.context-path=/api/v1


# =========================================================
# CONFIGURACION DE LA BASE DE DATOS (DATASOURCE)
# =========================================================
# Indica a Spring la URL de tu base de datos SQL Server.
# Reemplaza 'localhost' si tu DB esta en otro servidor.
# Reemplaza 'ristorinoDB' si usaste un nombre diferente.
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ristorinoDB;trustServerCertificate=true

# REEMPLAZA ESTO con tu usuario y contrasena de SQL Server
spring.datasource.username=sa
spring.datasource.password=123456

# Indica que driver especifico debe usar (el que agregamos como dependencia)
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


# =========================================================
# CONFIGURACION DE JDBC
# =========================================================
# JDBC no requiere configuración adicional, solo el datasource configurado arriba

# =========================================================
# SEGURIDAD Y AJUSTES DEL PORTAL
# =========================================================
security.jwt.secret=MiClaveJwtSuperSecretaDe32Caracteres
security.assets.base-path=/api/v1/public/assets
security.jwt.ttl-minutes=120

#ristorino.portal.nro=1
#ristorino.portal.idioma=1
